{% set name = "aiooss2" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06063e10efa6bc82d3d60dbb9cf2cbdc59640737752dc99fcd3bf9726e50be84
build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - oss2 >=2.17.0
    - aiohttp >=3.8.4

test:
  imports:
    - aiooss2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/aiooss2/
  summary: Async client for aliyun OSS(Object Storage Service) using oss2 and aiohttp/asyncio
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - karajan1001
