{% set name = "aiooss2" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 49db023f2b9c8bd8c9ed5d241c2ff3b42831b468b2cfa1b96ac6700b94fd053d
build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - oss2 >=2.17.0
    - aiohttp >=3.8.4

test:
  imports:
    - aiooss2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/aiooss2/
  summary: 'Async client for aliyun OSS(Object Storage Service) using oss2 and aiohttp/asyncio'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - karajan1001
